apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    app: {{ .Values.appLabel }}
    version: "v{{ .Values.image.version }}"
    app.kubernetes.io/name: {{ include "helmchart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - "{{ .Values.istio.virtualService.host }}{{ .Values.istio.virtualService.domain }}"
  gateways:
    - "{{ .Values.istio.virtualService.gateway.name }}"
  http:
  - name: "{{ .Values.appLabel }}-route"
    match:
    - uri:
        prefix: "{{ .Values.istio.virtualService.prefix }}"
    rewrite:
      uri: "{{ .Values.istio.virtualService.rewrite.uri }}"
    route:
    - destination:
        host: {{ include "helmchart.fullname" . }}
        port:
          number: {{ .Values.service.port }}
